pipeline {
    agent any

    stages {
        stage('Debug') {
            steps {
                sh 'ls -R'
            }
        }

        stage('Checkout') {
            steps {
                sh '''
                rm -rf * .[^.] .??*
                '''
                sh 'git clone https://github.com/alvaro-moises/asir-pfc-kubernetes.git .'
            }
        }

        stage('Build') {
            steps {
                sh 'docker build -t mi-registro/api:latest -f docker/Dockerfile.api .'
            }
        }

        stage('Test') {
            steps {
                sh 'mkdir -p reports'
                sh 'docker run --rm -v $PWD:/mnt/workspace -w /mnt/workspace python:3.13-slim bash -c "ls -l src && cat src/requirements.txt"'
            }
        }
    }
}
