pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'docker build -t mi-registro/api:latest -f docker/Dockerfile.api .'
      }
    }
    stage('Test') {
      steps {
        sh 'pytest --maxfail=1 --disable-warnings -q'
      }
    }
    stage('Push') {
      steps {
        withCredentials([string(credentialsId: 'docker-cred', variable: 'DOCKER_PASS')]) {
          sh 'echo $DOCKER_PASS | docker login mi-registro -u mi-user --password-stdin'
          sh 'docker push mi-registro/api:latest'
        }
      }
    }
    stage('Deploy') {
      steps {
        sh 'helm upgrade --install api ./charts/api -f charts/api/values.yaml'
      }
    }
  }
  post {
    always {
      junit '**/target/surefire-reports/*.xml'
      archiveArtifacts artifacts: '**/build/libs/*.jar', fingerprint: true
    }
  }
}
